### ISSUE TITLE
Make it parallel

### ISSUE THREAD

**Issue by AndreG-P** [KMCS-NII/planetext#3]
The program is pretty slow for huge databases. Because of the GIL in ruby, it is not so easy to parallelize the process. On the other hand, if we use JRuby (which can be used in parallel easily) has a very poor and extremely slow implementation of nokogiri (which is necessary to parse the HTML).

So either find a way around GIL in ruby or fix the performance issues in nokogiri in JRuby or found a new workaround.

**Comment by amadanmath** [comment]
GIL only works inside the Ruby process. I.e. if a process is CPU-bound, threads won't speed it up, but you can still parallelise it by spawning or forking new processes.

**Comment by AndreG-P** [comment]
In this case, the communication between the processes is more difficult to handle. Is there a ruby package that helps to do it?

**Comment by amadanmath** [comment]
I think [`parallel`](https://github.com/grosser/parallel) is probably the most popular gem for that.

**Comment by AndreG-P** [comment]
I don't have the ambition to further improve it. Maybe some day in the future :) To organize my issues better, I close it.
